/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Imagenes.DesktopConFondo;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Leila
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/selfish_dp.png")).getImage());
        
        ((DesktopConFondo) dpnEscritorio).setImagen("/Imagenes/principal_s.jpg");
        //ImageIcon selfish = new ImageIcon(getClass().getResource("/Imagenes/frmprincipal.png"));
        //ImageIcon icono=new ImageIcon(selfish.getImage().getScaledInstance(escritorio.getWidth(), escritorio.getHeight(),Image.SCALE_DEFAULT ));
        
        //escritorio.setIcon(icono);
        //asignarLookandfeel();
        //setExtendedState(MAXIMIZED_BOTH);
        //this.setLocationRelativeTo(null);
        //Mandamos el nombre del componente del label y la ruta donde se encuentra la imagen que
        //desean que se ajuste al tamaño del jlabel
        //rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1,"/Imagenes/frmprincipal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        dpnEscritorio = new DesktopConFondo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnRegistroEmpleado = new javax.swing.JMenuItem();
        jmnRegistroCliente = new javax.swing.JMenuItem();
        jmnRegistroProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnRegistroPedido = new javax.swing.JMenuItem();
        jmnListaPedidos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmnVentasRealizadas = new javax.swing.JMenuItem();
        jmnCierreCaja = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmnListaEmpleados = new javax.swing.JMenuItem();
        jmnListaClientes = new javax.swing.JMenuItem();
        jmnListaProductos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmnImprimir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpnEscritorio.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro_menu.png"))); // NOI18N
        jMenu1.setText("REGISTRO");

        jmnRegistroEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        jmnRegistroEmpleado.setText("EMPLEADO");
        jMenu1.add(jmnRegistroEmpleado);

        jmnRegistroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jmnRegistroCliente.setText("CLIENTE");
        jMenu1.add(jmnRegistroCliente);

        jmnRegistroProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        jmnRegistroProducto.setText("PRODUCTO");
        jMenu1.add(jmnRegistroProducto);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar_p.png"))); // NOI18N
        jMenu2.setText("PEDIDOS");

        jmnRegistroPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedido.png"))); // NOI18N
        jmnRegistroPedido.setText("REGISTRO DE PEDIDOS");
        jMenu2.add(jmnRegistroPedido);

        jmnListaPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedido.png"))); // NOI18N
        jmnListaPedidos.setText("PEDIDOS REALIZADO");
        jMenu2.add(jmnListaPedidos);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas_menu.png"))); // NOI18N
        jMenu5.setText("VENTAS");

        jmnVentasRealizadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas_menu.png"))); // NOI18N
        jmnVentasRealizadas.setText("VENTAS REALIZADAS");
        jMenu5.add(jmnVentasRealizadas);

        jmnCierreCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documento_pago.png"))); // NOI18N
        jmnCierreCaja.setText("CIERRE DE CAJA");
        jMenu5.add(jmnCierreCaja);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listas_menu.png"))); // NOI18N
        jMenu4.setText("LISTAS");

        jmnListaEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        jmnListaEmpleados.setText("EMPLEADOS");
        jMenu4.add(jmnListaEmpleados);

        jmnListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        jmnListaClientes.setText("CLIENTES");
        jMenu4.add(jmnListaClientes);

        jmnListaProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        jmnListaProductos.setText("PRODUCTOS");
        jMenu4.add(jmnListaProductos);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf.png"))); // NOI18N
        jMenu6.setText("REPORTE");

        jmnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        jmnImprimir.setText("IMPRIMIR");
        jMenu6.add(jmnImprimir);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jmnCierreCaja;
    public javax.swing.JMenuItem jmnImprimir;
    public javax.swing.JMenuItem jmnListaClientes;
    public javax.swing.JMenuItem jmnListaEmpleados;
    public javax.swing.JMenuItem jmnListaPedidos;
    public javax.swing.JMenuItem jmnListaProductos;
    public javax.swing.JMenuItem jmnRegistroCliente;
    public javax.swing.JMenuItem jmnRegistroEmpleado;
    public javax.swing.JMenuItem jmnRegistroPedido;
    public javax.swing.JMenuItem jmnRegistroProducto;
    public javax.swing.JMenuItem jmnVentasRealizadas;
    // End of variables declaration//GEN-END:variables
}
